# Generated by Django 5.2 on 2025-04-13 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Vorname')),
                ('last_name', models.CharField(max_length=50, verbose_name='Nachname')),
                ('street', models.CharField(max_length=100, verbose_name='Straße')),
                ('house_number', models.CharField(max_length=10, verbose_name='Hausnummer')),
                ('postal_code', models.CharField(max_length=10, verbose_name='PLZ')),
                ('country', models.CharField(max_length=50, verbose_name='Land')),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(blank=True, max_length=20, verbose_name='Mobiltelefon')),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='WhatsApp')),
                ('language', models.CharField(choices=[('de', 'Deutsch'), ('en', 'English')], default='de', max_length=2, verbose_name='Sprache')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Rabatt in %')),
            ],
        ),
    ]
