# Generated by Django 5.2 on 2025-04-18 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lenders', '0005_booking_custom_total_price_seasonalrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='lender',
            name='city',
            field=models.CharField(default='Berlin', max_length=50, verbose_name='Ort'),
        ),
    ]
