# Generated by Django 5.2 on 2025-04-18 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lenders', '0006_lender_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lender',
            name='house_number',
        ),
        migrations.RemoveField(
            model_name='lender',
            name='street',
        ),
        migrations.AddField(
            model_name='lender',
            name='address',
            field=models.CharField(default='Musterstraße 1', max_length=120, verbose_name='Adresse (Straße & Hausnummer)'),
            preserve_default=False,
        ),
    ]
