# Generated by Django 5.2 on 2025-04-19 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lenders', '0007_remove_lender_house_number_remove_lender_street_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='override_confirm',
            field=models.BooleanField(default=False, verbose_name='Ich bestätige die Warnung manuell'),
        ),
    ]
