# Generated by Django 5.2 on 2025-04-19 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lenders', '0010_alter_apartment_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='color',
            field=models.CharField(default='#cccccc', max_length=7, verbose_name='Farbe (für Kalender)'),
        ),
    ]
