# Generated by Django 5.2 on 2025-04-20 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lenders', '0011_alter_apartment_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seasonalrate',
            name='price_per_night',
        ),
        migrations.AddField(
            model_name='seasonalrate',
            name='percentage_adjustment',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Preis-Anpassung in %'),
            preserve_default=False,
        ),
    ]
