# Generated by Django 5.2 on 2025-04-21 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lenders', '0012_remove_seasonalrate_price_per_night_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentEmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('language', models.CharField(choices=[('de', 'Deutsch'), ('en', 'English')], max_length=2)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_log', to='lenders.payment')),
            ],
        ),
        migrations.CreateModel(
            name='SentConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('language', models.CharField(choices=[('de', 'Deutsch'), ('en', 'English')], max_length=2)),
                ('recipient', models.EmailField(max_length=254)),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lenders.lender')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lenders.payment')),
            ],
        ),
    ]
