# Generated by Django 5.2 on 2025-04-21 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lenders', '0014_payment_is_fixed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentconfirmation',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lenders.payment'),
        ),
    ]
