# Generated by Django 5.2 on 2025-04-21 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lenders', '0015_alter_sentconfirmation_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentconfirmation',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lenders.booking'),
        ),
    ]
